str="    welcome to sakkubhai   "
print(type(str))
print(str)
w=str.isspace()
print(w)
#how to access str
#indexing and slicing
print(str[0])
print(str[1:4])
#methods in string
#captilize()
print(str.capitalize())
#title()
print(str.title())
#lower()
print(str.lower())
#upper()
print(str.upper())
#swapcase()
print(str.swapcase())
#index(str)
print(str.index("t"))
#find(str)
print(str.find("s"))
print(str.find("z"))
#rfind(str)
print(str.rfind("w"))
#rindex()
print(str.rindex("i"))
#count(str)
print(str.count("e"))
print(str.count("k"))
#startwith(str)
print(str.startswith("w"))
print(str.startswith("i"))
#endswith(str)
print(str.endswith("i"))
#replace(old,new)
print(str.replace("s","a"))
#strip()
print(str.strip())
#rstrip()
print(str.rstrip())
#lstrip
print(str.lstrip())
#delimeter.joint(str)
e=["30","7","2004"]
print("/".join(e))
#split
v="welcome to bangalore"
e=v.split(",")
print(e)
#isdigit()
e="12345welcome"
w=e.isdigit()
print(w)
#islower()
w=e.islower()
print(w)
#isupper()
w=e.isupper()
print(w)
#isalpha()
w=e.isalpha()
print(w)
#isalnum()
s="welcome"
w=e.isalnum()
print(w)
#istitle()
w=e.istitle()
print(w)
#isspace()
w=e.isspace()
print(w)
#casefold
m="MY NAME IS VENKAT"
w=m.casefold()
print(w)



